# Generated by Django 3.2.16 on 2023-11-16 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccx', '0006_set_display_name_as_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcourseforedx',
            name='coach2',
            field=models.ForeignKey(blank=True, db_column='coach_id_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccx_coach2', to=settings.AUTH_USER_MODEL),
        ),
    ]